version: '3'

services:
    django_db:
        image: postgres:12.2
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - django_data:/var/lib/postgresql/data/

    client_db:
        image: postgres:12.2
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432"
        volumes:
            - client_data:/var/lib/postgresql/data/

    client_test_db:
        image: postgres:12.2
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432"
        volumes:
            - client_test_data:/var/lib/postgresql/data/

    web:
        build: .
        expose:
            - "8000"
        environment:
            - SECRET_KEY=jfghfdjgh374y237y7324hjbf732237f
            - DB_ENGINE=django.db.backends.postgresql
            - DB_HOST=django_db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_PORT=5432
            - DB_CLIENT_ENGINE=django.db.backends.postgresql
            - DB_CLIENT_HOST=client_db
            - DB_CLIENT_USER=postgres
            - DB_CLIENT_PASSWORD=postgres
            - DB_CLIENT_PORT=5432
            - DB_CLIENT_TEST_ENGINE=django.db.backends.postgresql
            - DB_CLIENT_TEST_HOST=client_test_db
            - DB_CLIENT_TEST_USER=postgres
            - DB_CLIENT_TEST_PASSWORD=postgres
            - DB_CLIENT_TEST_PORT=5432
        volumes:
            - web-django:/app
            - web-static:/app/static
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - django_db
            - client_db
            - client_test_db

volumes:
    web-django:
    web-static:
    django_data:
    client_data:
    client_test_data:
