version: '3.2'

services:
    django_db:
        image: postgres:12.2
        volumes:
            - django_data:/var/lib/postgresql/data/

    client_db:
        image: postgres:12.2
        volumes:
            - client_data:/var/lib/postgresql/data/
            - ./client_db_init.sql:/docker-entrypoint-initdb.d/client_db_init.sql
            # - client_db_init.sql:/var/lib/postgresql/client_db_init.sql:ro
        # entrypoint: /var/lib/postgresql/client_db_init.sql:/docker-entrypoint-initdb.d

    client_test_db:
        image: postgres:12.2
        volumes:
            - client_test_data:/var/lib/postgresql/data/
            - ./client_db_init.sql:/docker-entrypoint-initdb.d/client_db_init.sql
    
    web:
        image: salaah01/visualcsv
        ports:
            - "8000:8000"
        command: python ./visualCSV/manage.py runserver 0.0.0.0:8000
        depends_on:
            - django_db
            - client_db
            - client_test_db

volumes:
    web-static:
    django_data:
    client_data:
    client_test_data:
