version: '3.2'

services:
    django_db:
        image: postgres:12.2
        volumes:
            - django_data:/var/lib/postgresql/data/

    client_db:
        image: salaah01/visualcsv_client_db
        volumes:
            - client_data:/var/lib/postgresql/data/

    client_test_db:
        image: salaah01/visualcsv_client_db
        volumes:
            - client_test_data:/var/lib/postgresql/data/
        
    
    web:
        image: salaah01/visualcsv_web
        depends_on:
            - django_db
            - client_db
            - client_test_db

volumes:
    web-static:
    django_data:
    client_data:
    client_test_data:
