version: "3.8"

services:
  django_db:
    networks:
      - visual_csv
    restart: always

  client_db:
    networks:
      - visual_csv
    restart: always
  
  client_test_db:
    networks:
      - visual_csv
    restart: always
  
  web:
    networks:
      - visual_csv
    restart: always

  nginx:
    ports:
      - 8001:80
    networks: 
      - visual_csv
    restart: always

networks:
  visual_csv:
